[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.1"

[[constraint]]
  name = "k8s.io/client-go"
  branch = "master"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "v1.1.8"

[[constraint]]
  name = "github.com/michaelkipper/istio-client-go"
  version = "v0.1.1"

[prune]
  go-tests = true
[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"
